[package]
name = "sha2"
version = "1.0.0"
description = "Optimized implementation of all SHA2 functions"
repository = "https://github.com/research-ag/sha2"
keywords = [ "hash", "sha256", "sha512", "sha224", "sha384" ]
license = "Apache-2.0"

[dependencies]
core = "https://github.com/dfinity/motoko-core/releases/tag/implicits-17"

[dev-dependencies]
test = "2.1.1"
bench = "1.0.0"

[requirements]
moc = "0.16.3"

[toolchain]
wasmtime = "38.0.3"
moc = "0.16.3-implicits-21"
